export const CLEAR_ALL = 'CLEAR_ALL';
export const TOGGLE_POSITIVE_NEGATIVE = 'TOGGLE_POSITIVE_NEGATIVE';
export const CLICK_NUMBER = 'CLICK_NUMBER';
export const CLICK_DECIMAL = 'CLICK_DECIMAL';
export const CLICK_OPERATOR = 'CLICK_OPERATOR';
export const EVALUATE_RESULT = 'EVALUATE_RESULT';
export const CHECK_IF_CONTINUING_OPERATION = 'CHECK_IF_CONTINUING_OPERATION';